### ISSUE TITLE
Mega buggato broh

### ISSUE THREAD

**Issue by alessandro-massarenti** [eliapasquali/Lab1-MTSS-2022#3]

**Comment by eliapasquali** [comment]
Nessuna descrizione, non lo risolvo

**Comment by alessandro-massarenti** [comment]
MA come? dai dai risolvi

**Comment by alessandro-massarenti** [comment]
cos?

**Comment by eliapasquali** [comment]
![rick](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia1.tenor.com%2Fimages%2F23aeaaa34afd591deee6c163c96cb0ee%2Ftenor.gif%3Fitemid%3D7220603&f=1&nofb=1)
