### ISSUE TITLE
Got ukrained

### ISSUE THREAD

**Issue by AlecsFerra** [eliapasquali/Lab1-MTSS-2022#5]
**Describe the bug**
Occupied by russia

**To Reproduce**
1. Try to join NATO
2. Get invaded by Russia

**Expected behavior**
Join NATO

**Screenshots**
![image](https://user-images.githubusercontent.com/35380179/157037662-626b2583-33b8-4712-90ad-b61e97bcabb1.png)

**Desktop (please complete the following information):**
- European Continent

**Additional context**
ghost of texas

**Comment by eliapasquali** [comment]
![chad](https://i.kym-cdn.com/photos/images/original/001/501/991/902.gif)
